services:
  postgres:
    container_name: postgres_dev
    image: postgres 
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Uct123!}
    volumes:
      #default pgdata path: /var/lib/postgressql/data 
      - /var/lib/postgresql/data/dev-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped 

  pgadmin:
    container_name: pgadmin_container 
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-shuen.lyu@uct.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      #PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin 
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped 

networks:
  postgres:
    driver: bridge 

#volumes:
#    /var/lib/postgresql/data/dev-db:
#    ./pgadmin:
#there are no easy way to configure pgadmin log verbosity and it can be overwhelming at times
# logging:
#   driver: "none"

